# Generated by Django 3.2.7 on 2021-09-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20210929_1108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mene_Material',
            new_name='Menu_Material',
        ),
    ]
